spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?autoReconnect\=true
    username: developer
    password: developer

  thymeleaf:
    cache: false

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false